[package]
name = "deltav"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = {version = "0.6.2", features = ["serde-1"] }
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
